---
# tasks file for pip

- name: Import debian.yml if OS family is Debian
  ansible.builtin.import_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: Import install_centos.yml if OS family is CentOS
  ansible.builtin.import_tasks: install_centos.yml
  when: ansible_distribution == 'CentOS'
